name: CI

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm test

      - name: Empacotar a app
        run: npm pack

      - name: Publicar artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: '*.tgz'